server:
  port: 8080
  ssl:
    key-store: classpath:gtouyang.pfx
    key-store-password: nS2Nd2g2
    key-store-type: PKCS12
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
    register-with-eureka: false
    eureka-server-read-timeout-seconds: 2


spring:
  thymeleaf:
    cache: false
  mvc:
    favicon:
      enabled: false
  application:
    name: spike-system-consumer
token:
  secret: mySecret

feign:
  httpclient:
    connection-timeout: 20000

kafka:
  producer:
    bootstrapServers: localhost:9092
    retries: 3

    #16K
    batchSize: 16384

    lingerMs: 1

    #32M
    bufferMemory: 33554432