spring:
  profiles:
    active: Eureka-8761
---
spring:
  application:
    name: Eureka-Service-8761
  profiles: Eureka-8761
server:
  port: 8761

eureka:
  instance:
    hostname: eureka1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka2:8762/eureka/, http://eureka3:8763/eureka/

---
spring:
  application:
    name: Eureka-Service-8762
  profiles: Eureka-8762
server:
  port: 8762

eureka:
  instance:
    hostname: eureka2
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka3:8763/eureka/

---
spring:
  application:
    name: Eureka-Service-8763
  profiles: Eureka-8763
server:
  port: 8763

eureka:
  instance:
    hostname: eureka3
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/