spring:

  # redis config
  redis:
    jedis:
      pool:
        max-wait: 5000
        max-idle: 50
        min-idle: 5
    cluster:
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
    timeout: 500

  application:
    name: spike-system-order-service
server:
  port: 7090
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: order-service
info:
  app.name: ogic-spike-system-order-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

token:
  secret: mySecret


kafka:
  producer:
    bootstrapServers: localhost:9092
    retries: 3

    #16K
    batchSize: 16384

    lingerMs: 1

    #32M
    bufferMemory: 33554432

  consumer:
    bootstrapServers: localhost:9092
    groupId: order-service
    enableAutoCommit: false
    autoCommitIntervalMs: 1000
    sessionTimeoutMs: 30000
    maxPollRecords: 100

    #earliest,latest
    autoOffsetReset: earliest