spring:

  # redis config
  redis:
    host: 127.0.0.1
    port: 6379

  application:
    name: spike-system-order-service
server:
  port: 7090
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: order-service
info:
  app.name: ogic-spike-system-order-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

token:
  secret: mySecret
