spring:
  application:
    name: spike-system-pay-service
server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: pay-service
info:
  app.name: ogic-spike-system-pay-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
kafka:
  producer:
    bootstrapServers: localhost:9092
    retries: 3

    #16K
    batchSize: 16384

    lingerMs: 1

    #32M
    bufferMemory: 33554432

  consumer:
    bootstrapServers: localhost:9092
    groupId: order-service
    enableAutoCommit: false
    autoCommitIntervalMs: 1000
    sessionTimeoutMs: 30000
    maxPollRecords: 100

    #earliest,latest
    autoOffsetReset: earliest