spring:

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  application:
    name: spike-system-pay-service
server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: pay-service
info:
  app.name: ogic-spike-system-pay-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
