spring:
  application:
    name: spike-system-pay-service

  #MySQL config
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/spike_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ogic
    password: pass

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500

  # redis config
  redis:
    jedis:
      pool:
        max-wait: 5000
        max-idle: 50
        min-idle: 5
    cluster:
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
    timeout: 500

server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: pay-service
info:
  app.name: ogic-spike-system-pay-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
kafka:
  producer:
    bootstrapServers: localhost:9092
    retries: 3

    #16K
    batchSize: 16384

    lingerMs: 1

    #32M
    bufferMemory: 33554432

  consumer:
    bootstrapServers: localhost:9092
    groupId: pay-service
    enableAutoCommit: false
    autoCommitIntervalMs: 1000
    sessionTimeoutMs: 30000
    maxPollRecords: 100

    #earliest,latest
    autoOffsetReset: earliest

#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #启动驼峰命名法