spring:
  application:
    name: spike-system-sync-service

  # redis config
  redis:
    jedis:
      pool:
        max-wait: 5000
        max-idle: 50
        min-idle: 5
    cluster:
      nodes:
        - 127.0.0.1:7000
        - 127.0.0.1:7001
        - 127.0.0.1:7002
        - 127.0.0.1:7003
        - 127.0.0.1:7004
        - 127.0.0.1:7005
    timeout: 500

server:
  port: 18000
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: sync-service
info:
  app.name: ogic-spike-system-sync-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

token:
  secret: mySecret

kafka:
  consumer:
    bootstrapServers: localhost:9092
    groupId: sync-service
    enableAutoCommit: false
    autoCommitIntervalMs: 1000
    sessionTimeoutMs: 30000
    maxPollRecords: 100

    #earliest,latest
    autoOffsetReset: earliest