kind: Service
apiVersion: v1
metadata:
  name: spike-system-service
spec:
  type: NodePort
  selector:
    app: spike-system-consumer
  ports:
    - protocol: TCP
      port: 6666
      targetPort: 8080
      nodePort: 32080

