spring:
  application:
    name: spike-system-shop-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://127.0.0.1:3306/spike_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ogic
    password: pass

    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
server:
  port: 8300
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: shop-service
info:
  app.name: ogic-spike-system-shop-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #启动驼峰命名法