# Server configuration
server:
  port: 8090

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  application:
    name: spike-system-auth-service

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: auth-service
info:
  app.name: ogic-spike-system-auth-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #启动驼峰命名法
    use-generated-keys: true


# token
token:
  secret: mySecret

