# Server configuration
server:
  port: 8090

# Spring configuration
spring:
  jackson:
    serialization:
      INDENT_OUTPUT: true
  datasource:
    username: ogic
    password: pass
    url: jdbc:mysql://localhost:3306/spike_db
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    #针对Druid的一些配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  application:
    name: spike-system-auth-service

# Logging configuration
logging:
  level:
    org.springframework:
      data: DEBUG
      security: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: auth-service
info:
  app.name: ogic-spike-system-auth-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #启动驼峰命名法
    use-generated-keys: true


# token
token:
  secret: mySecret
  life: 86400
