spring:
  application:
    name: spike-system-product-service
server:
  port: 7080
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/, http://eureka2:8762/eureka/, http://eureka3:8763/eureka/
  instance:
    instance-id: product-service
info:
  app.name: ogic-spike-system-product-service
  company.name: ogic.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

#mybatis config
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #启动驼峰命名法
    use-generated-keys: true